<?php

declare(strict_types=1);

return [
    'hero_badge' => 'Free Health & Safety Healthcheck',
    'hero_title_line_1' => 'Find the gaps.',
    'hero_title_line_2' => 'Know what to do next.',
    'hero_intro' => 'In around 3–4 minutes, get a practical snapshot of your Health & Safety, Fire Safety, Legionella and Asbestos arrangements — with clear actions showing what may need attention.',
    'primary_cta' => 'Start my free Healthcheck',
    'hero_micro' => 'Free • No account needed • Instant results • Downloadable action plan',
    'hero_topic_1' => 'Health & Safety',
    'hero_topic_2' => 'Fire Safety',
    'hero_topic_3' => 'Legionella',
    'hero_topic_4' => 'Asbestos',

    'show_authority' => 1,
    'authority_eyebrow' => 'Built by specialists',
    'authority_heading' => 'One specialist team. Four critical compliance disciplines.',
    'authority_body' => 'Acorn Safety Services helps organisations understand and manage Health & Safety, Fire Safety, Legionella and Asbestos risks through practical advice, assessments and ongoing support.',

    'show_benefits' => 1,
    'benefits_eyebrow' => 'What you get',
    'benefits_heading' => 'More than a checklist',
    'benefits_intro' => 'The Healthcheck is designed to help you quickly understand where your current arrangements appear strong and where further attention may be worthwhile.',
    'benefit_1_title' => 'Your priority actions',
    'benefit_1_body' => 'See the areas that may need attention first.',
    'benefit_2_title' => 'Areas worth reviewing',
    'benefit_2_body' => 'Identify arrangements that may need checking or confirming.',
    'benefit_3_title' => 'What looks good',
    'benefit_3_body' => 'See where your answers did not identify an obvious gap.',
    'benefit_4_title' => 'A practical action plan',
    'benefit_4_body' => 'Get clear next steps, guidance and a downloadable report.',

    'show_how_it_works' => 1,
    'how_eyebrow' => 'How it works',
    'how_heading' => 'A clearer picture in a few minutes',
    'how_1_title' => 'Answer straightforward questions',
    'how_1_body' => 'No jargon-heavy audit forms. We only show checks relevant to your organisation.',
    'how_2_title' => 'See where things stand',
    'how_2_body' => 'Your results are grouped into priority actions, areas worth reviewing and areas looking good.',
    'how_3_title' => 'Know what to do next',
    'how_3_body' => 'Receive practical guidance and a downloadable Healthcheck report you can use as an action plan.',

    'show_expertise' => 1,
    'expertise_eyebrow' => 'Four areas. One joined-up view.',
    'expertise_heading' => 'The Healthcheck looks across the areas businesses often need to manage together',
    'expertise_hs_title' => 'Health & Safety',
    'expertise_hs_body' => 'Competent support, policies, risk assessments, training, first aid, incident management and workplace arrangements.',
    'expertise_fire_title' => 'Fire Safety',
    'expertise_fire_body' => 'Fire Risk Assessments, emergency arrangements and the management of fire precautions.',
    'expertise_legionella_title' => 'Legionella',
    'expertise_legionella_body' => 'Responsibility for water systems, risk assessment and appropriate control arrangements.',
    'expertise_asbestos_title' => 'Asbestos',
    'expertise_asbestos_body' => 'Existing asbestos information, management responsibilities and arrangements for older non-domestic buildings.',

    'show_insight' => 1,
    'insight_eyebrow' => 'Why take the Healthcheck?',
    'insight_heading' => 'Problems are easier to deal with when you can see them clearly.',
    'insight_body_1' => 'Health & Safety problems are often not caused by businesses doing nothing. More commonly, responsibilities are unclear, documents have become outdated, actions have not been followed through, or nobody is quite sure whether an arrangement still meets the organisation’s needs.',
    'insight_body_2' => 'The Acorn Healthcheck gives you a structured way to step back and look at the important areas together.',
    'insight_callout_heading' => 'You don’t need to know every answer before you start.',
    'insight_callout_body' => '“Not sure” is a perfectly valid answer — and often one of the most useful. We’ll flag the area for review rather than forcing you to guess.',

    'show_preview' => 1,
    'preview_eyebrow' => 'A useful result, not just a score',
    'preview_heading' => 'See exactly where to focus',
    'preview_intro' => 'Your Healthcheck gives you an immediate view of what may need attention and a practical next step for each issue.',
    'preview_priority_count' => '2',
    'preview_priority_label' => 'Priority actions',
    'preview_review_count' => '4',
    'preview_review_label' => 'Worth reviewing',
    'preview_good_count' => '10',
    'preview_good_label' => 'Areas looking good',
    'preview_card_eyebrow' => 'Example first priority',
    'preview_card_heading' => 'Fire Risk Assessment',
    'preview_card_body' => 'Your answers suggest that the current Fire Risk Assessment may need attention.',
    'preview_card_next_label' => 'Do this next',
    'preview_card_next_text' => 'Confirm that a suitable and current assessment is in place and that identified actions are being managed.',

    'show_support' => 1,
    'support_eyebrow' => 'How Acorn Safety Services can help',
    'support_heading' => 'Knowing the gaps is the first step. Fixing them is what matters.',
    'support_intro' => 'If your Healthcheck identifies something that needs attention, you don’t have to work out the next step alone. Acorn Safety Services can help you review the issue, confirm what is required and put practical arrangements in place.',
    'support_hs_title' => 'Health & Safety support',
    'support_hs_body' => 'Competent-person support, policies, assessments, training and ongoing advice.',
    'support_fire_title' => 'Fire Safety',
    'support_fire_body' => 'Fire Risk Assessments and support addressing identified actions.',
    'support_legionella_title' => 'Legionella',
    'support_legionella_body' => 'Risk assessments and practical monitoring and control support.',
    'support_asbestos_title' => 'Asbestos',
    'support_asbestos_body' => 'Surveys, management arrangements and specialist asbestos support.',
    'audit_cta_text' => 'Request a free Compliance Audit',

    'show_faq' => 1,
    'faq_eyebrow' => 'Before you start',
    'faq_heading' => 'Frequently asked questions',
    'faq_1_question' => 'How long does it take?',
    'faq_1_answer' => 'Most businesses should complete the Healthcheck in around 3–4 minutes.',
    'faq_2_question' => 'Do I need to create an account?',
    'faq_2_answer' => 'No. You can complete the Healthcheck without creating an account.',
    'faq_3_question' => 'What happens to my answers?',
    'faq_3_answer' => 'Your answers are used to prepare your personalised results and Healthcheck report.',
    'faq_4_question' => 'Is this a formal Health & Safety audit?',
    'faq_4_answer' => 'No. It is an indicative self-assessment designed to highlight areas that may merit attention. It is not legal advice or confirmation of compliance.',
    'faq_5_question' => 'What if I don’t know an answer?',
    'faq_5_answer' => 'Select “Not sure”. The Healthcheck will flag the area for review rather than forcing you to guess.',

    'show_final_cta' => 1,
    'final_eyebrow' => 'Free Health & Safety Healthcheck',
    'final_heading' => 'Ready to see where things stand?',
    'final_body' => 'Take the free Acorn Health & Safety Healthcheck and leave with a clearer picture of what looks good, what may need attention and what to do next.',
    'final_micro' => 'Around 3–4 minutes • No account required • Personalised action plan',
    'disclaimer' => 'This is an indicative self-assessment based on the information you provide. It is not a formal audit, legal advice or confirmation of compliance.',
];
