<!doctype html>
<html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Health &amp; Safety Healthcheck Report</title><?php wp_head(); ?></head>
<body><main class="acorn-hc acorn-hc__report">
<header><?php if($report['branding']['logo_url']):?><img src="<?php echo esc_url($report['branding']['logo_url']);?>" alt="Acorn Safety Services"><?php endif;?><p>Acorn Safety Services</p><h1>Health &amp; Safety Healthcheck Report</h1><p>Covering Health &amp; Safety · Fire · Legionella · Asbestos</p><p><strong><?php echo esc_html($report['meta']['company']); ?></strong> · <?php echo esc_html($report['meta']['assessment_date']); ?> · Self-assessment report</p></header>
<section><h2>Executive summary</h2><dl class="acorn-hc__counts"><div><dt>Areas assessed</dt><dd><?php echo (int)$report['meta']['areas_assessed']; ?></dd></div><div><dt>Priority actions</dt><dd><?php echo (int)$report['summary']['priority_count']; ?></dd></div><div><dt>Areas to review</dt><dd><?php echo (int)$report['summary']['review_count']; ?></dd></div><div><dt>No obvious gap identified</dt><dd><?php echo (int)$report['summary']['addressed_count']; ?></dd></div></dl><ul class="acorn-hc__pillars"><?php foreach($report['pillars'] as $pillar): ?><li><strong><?php echo esc_html($pillar['label']); ?>:</strong> <?php echo esc_html(ucwords(str_replace('_',' ',$pillar['status']))); ?></li><?php endforeach; ?></ul><p><?php echo esc_html($report['disclaimer']); ?></p><p><a href="<?php echo esc_url(trailingslashit($reportUrl).'pdf/'); ?>">Download PDF report</a></p></section>
<?php foreach(['addressed','review','priority'] as $type): ?><section><h2><?php echo esc_html($report['sections'][$type]['label']); ?></h2><?php if(!$report[$type]): ?><p>No findings in this section.</p><?php endif; ?><?php foreach($report[$type] as $item): ?><article class="acorn-hc__finding"><h3><?php echo esc_html($item['recommendation']['heading'] ?? $item['positive_text']); ?></h3><?php if($type==='addressed'): ?><p><?php echo esc_html($item['positive_text']); ?></p><?php else: ?><p><strong>What we identified:</strong> <?php echo esc_html($item['recommendation']['identified_text']); ?></p><p><strong>Recommended next step:</strong> <?php echo esc_html($item['recommendation']['next_step_text']); ?></p><p><strong>Why this matters:</strong> <?php echo esc_html($item['recommendation']['why_text']); ?></p><p><strong>What good looks like:</strong> <?php echo esc_html($item['recommendation']['good_looks_text']); ?></p><?php endif; ?></article><?php endforeach; ?></section><?php endforeach; ?>
<section><h2>Action summary</h2><table><thead><tr><th>Status</th><th>Area</th><th>Recommended action</th></tr></thead><tbody><?php foreach($report['action_summary'] as $item): ?><tr><td><?php echo esc_html($item['finding_status']==='priority'?'Priority action':'Review recommended'); ?></td><td><?php echo esc_html($item['recommendation']['heading']); ?></td><td><?php echo esc_html($item['recommendation']['next_step_text']); ?></td></tr><?php endforeach; ?></tbody></table></section>
<section class="acorn-hc__support"><h2><?php echo esc_html($report['support']['heading']); ?></h2><p>If you do not have the relevant expertise internally, Acorn can assist with areas including Health &amp; Safety, Fire Safety, Legionella and Asbestos.</p><a class="acorn-hc__primary" href="<?php echo esc_url($report['support']['cta_url']); ?>"><?php echo esc_html($report['support']['cta_label']); ?></a></section>
<footer><p><a href="<?php echo esc_url($report['branding']['website']); ?>">Acorn Safety Services</a> · <?php echo esc_html($report['branding']['phone']); ?><?php if($report['privacy_policy_url']):?> · <a href="<?php echo esc_url($report['privacy_policy_url']); ?>">Privacy policy</a><?php endif;?></p></footer></main><?php wp_footer(); ?></body></html>
