<?php

declare(strict_types=1);
namespace Acorn\SafetyHealthcheck\Admin;

use Acorn\SafetyHealthcheck\Content\{ContentPublisher, ContentVersionRepository, QuestionRepository};
use Acorn\SafetyHealthcheck\Database\Schema;

final class ContentPage
{
    public function render(): void
    {
        if(!current_user_can('manage_acorn_healthcheck'))wp_die('Forbidden',403);global$wpdb;$publisher=new ContentPublisher();
        if($_SERVER['REQUEST_METHOD']==='POST'){check_admin_referer('acorn_hc_content');$action=sanitize_key($_POST['content_action']??'');try{if($action==='create_draft')$publisher->createDraftFromPublished(get_current_user_id());elseif($action==='publish')$publisher->publish(absint($_POST['version_id']),get_current_user_id());elseif($action==='question'){$publisher->updateDraftQuestion(absint($_POST['version_id']),sanitize_key($_POST['question_key']),['question_text'=>wp_unslash($_POST['question_text']??''),'help_text'=>wp_unslash($_POST['help_text']??''),'module_key'=>$_POST['module_key']??'','applicability'=>json_decode(wp_unslash($_POST['applicability_json']??''),true,512,JSON_THROW_ON_ERROR),'source'=>['title'=>wp_unslash($_POST['source_title']??''),'url'=>wp_unslash($_POST['source_url']??'')],'reviewed_by'=>wp_unslash($_POST['reviewed_by']??''),'last_reviewed'=>$_POST['last_reviewed']??'','next_review'=>$_POST['next_review']??'']);}elseif($action==='recommendation'){$publisher->updateDraftRecommendation(absint($_POST['version_id']),absint($_POST['recommendation_id']),['jurisdiction'=>$_POST['jurisdiction']??'*','finding_status'=>$_POST['finding_status']??'','heading'=>wp_unslash($_POST['heading']??''),'identified_text'=>wp_unslash($_POST['identified_text']??''),'next_step_text'=>wp_unslash($_POST['next_step_text']??''),'why_text'=>wp_unslash($_POST['why_text']??''),'good_looks_text'=>wp_unslash($_POST['good_looks_text']??''),'service_tags'=>array_filter(array_map('trim',explode(',',wp_unslash($_POST['service_tags']??'')))),'source'=>['title'=>wp_unslash($_POST['source_title']??''),'url'=>wp_unslash($_POST['source_url']??'')],'sort_rank'=>$_POST['sort_rank']??100]);}echo'<div class="notice notice-success"><p>Content action completed.</p></div>';}catch(\Throwable$error){echo'<div class="notice notice-error"><p>'.esc_html($error->getMessage()).'</p></div>';}}
        $published=(new ContentVersionRepository())->getPublished();$draft=$wpdb->get_row("SELECT * FROM ".Schema::table('content_versions')." WHERE status='draft' ORDER BY id DESC LIMIT 1",ARRAY_A);echo'<div class="wrap"><h1>Questions &amp; Recommendations</h1><p>Published version '.esc_html($published['version_key']).' is immutable. All edits below target a draft.</p>';
        if(!$draft){echo'<form method="post">';wp_nonce_field('acorn_hc_content');echo'<input type="hidden" name="content_action" value="create_draft">';submit_button('Create draft from published');echo'</form></div>';return;}
        $questions=(new QuestionRepository())->forVersion((int)$draft['id']);$selected=sanitize_key($_GET['question']??($questions[0]['question_key']??''));$question=(new QuestionRepository())->get((int)$draft['id'],$selected);echo'<p>Editing draft '.esc_html($draft['version_key']).'</p><form method="get"><input type="hidden" name="page" value="acorn-healthcheck-content"><select name="question">';foreach($questions as$q)echo'<option '.selected($selected,$q['question_key'],false).' value="'.esc_attr($q['question_key']).'">'.esc_html($q['question_key']).'</option>';echo'</select>';submit_button('Edit','secondary','',false);echo'</form>';
        if($question){$source=json_decode($question['source_json'],true);$source=$source['default']??$source;echo'<h2>Question</h2><form method="post">';wp_nonce_field('acorn_hc_content');echo'<input type="hidden" name="content_action" value="question"><input type="hidden" name="version_id" value="'.(int)$draft['id'].'"><input type="hidden" name="question_key" value="'.esc_attr($selected).'">';$this->textarea('question_text',$question['question_text']);$this->textarea('help_text',$question['help_text']);$this->input('module_key',$question['module_key']);$this->textarea('applicability_json',wp_json_encode(json_decode($question['applicability_json'],true),JSON_PRETTY_PRINT));$this->input('source_title',$source['title']??'');$this->input('source_url',$source['url']??'');$this->input('reviewed_by',$question['reviewed_by']);$this->input('last_reviewed',$question['last_reviewed'],'date');$this->input('next_review',$question['next_review'],'date');submit_button('Save draft question');echo'</form>';
        $recommendations=$wpdb->get_results($wpdb->prepare('SELECT * FROM '.Schema::table('recommendations').' WHERE content_version_id=%d AND question_key=%s ORDER BY answer_value,jurisdiction',(int)$draft['id'],$selected),ARRAY_A);echo'<h2>Recommendation variants</h2>';foreach($recommendations as$recommendation){$recSource=json_decode($recommendation['source_json'],true);echo'<details><summary>'.esc_html($recommendation['answer_value'].' / '.$recommendation['jurisdiction']).'</summary><form method="post">';wp_nonce_field('acorn_hc_content');echo'<input type="hidden" name="content_action" value="recommendation"><input type="hidden" name="version_id" value="'.(int)$draft['id'].'"><input type="hidden" name="recommendation_id" value="'.(int)$recommendation['id'].'">';foreach(['jurisdiction','finding_status','heading']as$field)$this->input($field,$recommendation[$field]);foreach(['identified_text','next_step_text','why_text','good_looks_text']as$field)$this->textarea($field,$recommendation[$field]);$this->input('service_tags',implode(',',json_decode($recommendation['service_tags_json'],true)?:[]));$this->input('source_title',$recSource['title']??'');$this->input('source_url',$recSource['url']??'');$this->input('sort_rank',$recommendation['sort_rank'],'number');submit_button('Save recommendation');echo'</form></details>';}}
        echo'<h2>Publish</h2><p>Publishing is blocked until every technical-review and content-completeness check passes.</p><form method="post">';wp_nonce_field('acorn_hc_content');echo'<input type="hidden" name="content_action" value="publish"><input type="hidden" name="version_id" value="'.(int)$draft['id'].'">';submit_button('Publish reviewed draft','primary');echo'</form></div>';
    }
    private function input(string$name,$value,string$type='text'):void{echo'<p><label><strong>'.esc_html(ucwords(str_replace('_',' ',$name))).'</strong><br><input class="regular-text" type="'.esc_attr($type).'" name="'.esc_attr($name).'" value="'.esc_attr((string)$value).'" required></label></p>';}
    private function textarea(string$name,string$value):void{echo'<p><label><strong>'.esc_html(ucwords(str_replace('_',' ',$name))).'</strong><br><textarea class="large-text" rows="4" name="'.esc_attr($name).'" required>'.esc_textarea($value).'</textarea></label></p>';}
}
